@startuml
' Baseline SMRT Workflow
!theme ihe-ro from ./themes
title SMRT Baseline Workflow
hide footbox

participant ROIS
participant TMS
participant OST

== Patient Registration ==
ROIS -> TMS : Patient Identity Management [ITI-30]
ROIS -> TMS : Patient Encounter Management [ITI-31]
ROIS -> TMS : Send Patient Photo [FHIR Message]
...
ROIS -[#a8a8a8]> ROIS : Schedule Appointments

loop For each appointment
  ||10||
  ROIS -> TMS : Appointment Notification [RAD-48]
  ||10||
end
...
== Treatment Planning ==
TMS -[#a8a8a8]> TMS : Import, Approve Treatment Plan
TMS -> ROIS : Report Planning Artifacts Ready [FHIR Message]
ROIS -> OST : Retrieve Planning Artifacts [DICOM]
...
== Treatment Delivery Preparation ==
TMS -[#a8a8a8]> TMS : Enrich Plan for Delivery,\nPrepare Sessions,\nApprove Treatment
TMS -> ROIS : Report Deliverable Plan Artifact Ready [FHIR Message]
ROIS -> OST : Retrieve Deliverable Plan Artifact [DICOM]
...
== Treatment Delivery ==
loop For each treatment session
...
  alt Patient Check-in
    ROIS -> TMS : Appointment Notification [RAD-48]
    note right of ROIS : SIU^S13 - Reschedule Bookings
  else
    TMS -> ROIS : Appointment Notification [RAD-48]
    note left of TMS : SIU^S13 - Reschedule Bookings
  end
...
  TMS -[#a8a8a8]> TMS : Manage Treatment Session Delivery
  TMS -> ROIS : Report Delivery Artifacts Ready [FHIR Message]
  ROIS -> OST : Retrieve Delivery Artifacts [DICOM]
  ...
  ROIS -[#a8a8a8]> ROIS : Track Treatment Progress
  ||10||
end

@enduml
